markdown: kramdown
kramdown:
  parse_block_html: false
  parse_span_html: false
collections:
  lxc:
    output: true
    permalink: /lxc/:slug/
plugins: []
exclude: [vendor, Gemfile, Gemfile.lock, README.md, _plugins, _addon, _pve, _vm, scripts, tools, misc, .github, .devcontainer, assets, docs, _ast]
permalink: pretty
