#!/usr/bin/env bash
REPO_BASE="${REPO_BASE:-https://raw.githubusercontent.com/scripts-underground/proxmox/main}"

# Copyright (c) 2021-2026 community-scripts ORG
# Author: Slaviša Arežina (tremor021)
# License: MIT | https://raw.githubusercontent.com/scripts-underground/proxmox/main/LICENSE
# Source: https://www.powerdns.com/

# shellcheck disable=SC2034
APP="PowerDNS"
var_tags="${var_tags:-dns}"
var_cpu="${var_cpu:-1}"
var_ram="${var_ram:-1024}"
var_disk="${var_disk:-4}"
var_os="${var_os:-debian}"
var_version="${var_version:-13}"
var_arm64="${var_arm64:-yes}"
var_unprivileged="${var_unprivileged:-1}"

function escape_sql() {
  printf '%s' "$1" | sed "s/'/''/g"
}

function install_script() {
  msg_info "Installing Dependencies"
  $STD apt install -y sqlite3
  msg_ok "Installed Dependencies"

  PHP_VERSION="8.3" PHP_APACHE="YES" PHP_FPM="YES" PHP_MODULE="gettext,tokenizer,sqlite3,ldap" setup_php

  setup_deb822_repo \
    "pdns" \
    "https://repo.powerdns.com/FD380FBB-pub.asc" \
    "http://repo.powerdns.com/debian" \
    "trixie-auth-50"

  cat << EOF > /etc/apt/preferences.d/auth-50
Package: pdns-*
Pin: origin repo.powerdns.com
Pin-Priority: 600
EOF

  msg_info "Setting up PowerDNS"
  $STD apt install -y \
    pdns-server \
    pdns-backend-sqlite3
  sed -i 's/^launch=$/# launch=/' /etc/powerdns/pdns.conf
  rm -f /etc/powerdns/pdns.d/bind.conf
  cat << EOF > /etc/powerdns/pdns.d/gsqlite3.conf
launch=gsqlite3
gsqlite3-database=/opt/poweradmin/powerdns.db
EOF
  msg_ok "Setup PowerDNS"

  fetch_and_deploy_gh_release "poweradmin" "poweradmin/poweradmin" "tarball"

  msg_info "Setting up Poweradmin"
  sqlite3 /opt/poweradmin/powerdns.db < /opt/poweradmin/sql/poweradmin-sqlite-db-structure.sql
  sqlite3 /opt/poweradmin/powerdns.db < /opt/poweradmin/sql/pdns/49/schema.sqlite3.sql
  PA_ADMIN_USERNAME="admin"
  PA_ADMIN_EMAIL="admin@example.com"
  PA_ADMIN_FULLNAME="Administrator"
  PA_ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/" | cut -c1-16)
  PA_SESSION_KEY=$(openssl rand -base64 75 | tr -dc 'A-Za-z0-9^@#!(){}[]%_\-+=~' | head -c 50)
  PASSWORD_HASH=$(php -r "echo password_hash(\$argv[1], PASSWORD_DEFAULT);" -- "${PA_ADMIN_PASSWORD}" 2> /dev/null)
  sqlite3 /opt/poweradmin/powerdns.db "INSERT INTO users (username, password, fullname, email, description, perm_templ, active, use_ldap) \
    VALUES ('$(escape_sql "${PA_ADMIN_USERNAME}")', '$(escape_sql "${PASSWORD_HASH}")', '$(escape_sql "${PA_ADMIN_FULLNAME}")', \
    '$(escape_sql "${PA_ADMIN_EMAIL}")', 'System Administrator', 1, 1, 0);"

  cat << EOF > ~/poweradmin.creds
Admin Username: ${PA_ADMIN_USERNAME}
Admin Password: ${PA_ADMIN_PASSWORD}
EOF

  cat << EOF > /opt/poweradmin/config/settings.php
<?php

/**
 * Poweradmin Settings Configuration File
 *
 * Generated by the installer on $(date +"%Y-%m-%d %H:%M:%S")
 */

return [
    /**
     * Database Settings
     */
    'database' => [
        'type' => 'sqlite',
        'file' => '/opt/poweradmin/powerdns.db',
    ],

    /**
     * Security Settings
     */
    'security' => [
        'session_key' => '${PA_SESSION_KEY}',
    ],

    /**
     * Interface Settings
     */
    'interface' => [
        'language' => 'en_EN',
    ],

    /**
     * DNS Settings
     */
    'dns' => [
        'hostmaster' => 'localhost.lan',
        'ns1' => '8.8.8.8',
        'ns2' => '9.9.9.9',
    ]
];
EOF
  rm -rf /opt/poweradmin/install
  msg_ok "Setup Poweradmin"

  msg_info "Creating Service"
  rm /etc/apache2/sites-enabled/000-default.conf
  cat << EOF > /etc/apache2/sites-enabled/poweradmin.conf
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /opt/poweradmin

    <Directory /opt/poweradmin>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    RewriteEngine On
    RewriteRule ^/update(.*)\$ /dynamic_update.php [L]
    RewriteRule ^/nic/update(.*)\$ /dynamic_update.php [L]
</VirtualHost>
EOF
  $STD a2enmod rewrite headers
  chown -R www-data:pdns /opt/poweradmin
  chmod 775 /opt/poweradmin
  chown pdns:pdns /opt/poweradmin/powerdns.db
  chmod 664 /opt/poweradmin/powerdns.db
  usermod -aG pdns www-data
  $STD systemctl restart pdns apache2
  msg_ok "Created Service"
}

function post_install_script() {
  msg_ok "Completed successfully!\n"
  echo -e "${CREATING}${GN}${APP} setup has been successfully initialized!${CL}"
  echo -e "${INFO}${YW}Access it using the following URL:${CL}"
  echo -e "${GATEWAY}${BGN}http://${IP}${CL}"
}

function update_script() {
  header_info
  check_container_storage
  check_container_resources
  if [[ ! -d /opt/poweradmin ]]; then
    msg_error "No ${APP} Installation Found!"
    exit
  fi

  msg_info "Updating PowerDNS"
  $STD apt update
  $STD apt install -y --only-upgrade pdns-server pdns-backend-sqlite3
  msg_ok "Updated PowerDNS"

  if check_for_gh_release "poweradmin" "poweradmin/poweradmin"; then
    msg_info "Backing up Configuration"
    cp /opt/poweradmin/config/settings.php /opt/poweradmin_settings.php.bak
    cp /opt/poweradmin/powerdns.db /opt/poweradmin_powerdns.db.bak
    msg_ok "Backed up Configuration"

    CLEAN_INSTALL=1 fetch_and_deploy_gh_release "poweradmin" "poweradmin/poweradmin" "tarball"

    msg_info "Updating Poweradmin"
    cp /opt/poweradmin_settings.php.bak /opt/poweradmin/config/settings.php
    cp /opt/poweradmin_powerdns.db.bak /opt/poweradmin/powerdns.db
    rm -rf /opt/poweradmin/install
    rm -f /opt/poweradmin_settings.php.bak /opt/poweradmin_powerdns.db.bak
    chown -R www-data:pdns /opt/poweradmin
    chmod 775 /opt/poweradmin
    chown pdns:pdns /opt/poweradmin/powerdns.db
    chmod 664 /opt/poweradmin/powerdns.db
    msg_ok "Updated Poweradmin"

    msg_info "Restarting Services"
    systemctl restart pdns apache2
    msg_ok "Restarted Services"
    msg_ok "Updated successfully!"
  fi
  exit
}

# shellcheck disable=SC1090
source <(curl -fsSL "$REPO_BASE/misc/bootstrap/lxc")
