#!/usr/bin/env bash
REPO_BASE="${REPO_BASE:-https://raw.githubusercontent.com/scripts-underground/proxmox/main}"

# Sourced by lxc.bootstrap — never executed directly
# Copyright (c) 2021-2026 community-scripts ORG
# Author: pshankinclarke (lazarillo)
# License: MIT | https://raw.githubusercontent.com/scripts-underground/proxmox/main/LICENSE
# Source: https://valkey.io/

# shellcheck disable=SC2034
# Read by the framework - shellcheck cannot see the caller
APP="Valkey"
var_tags="${var_tags:-database}"
var_cpu="${var_cpu:-1}"
var_ram="${var_ram:-1024}"
var_disk="${var_disk:-4}"
var_os="${var_os:-debian}"
var_version="${var_version:-13}"
var_arm64="${var_arm64:-yes}"
var_unprivileged="${var_unprivileged:-1}"

function install_script() {
  msg_info "Installing Valkey"
  $STD apt update
  $STD apt install -y valkey openssl
  sed -i 's/^bind .*/bind 0.0.0.0/' /etc/valkey/valkey.conf

  PASS="$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c32)"
  echo "requirepass $PASS" >> /etc/valkey/valkey.conf
  echo "$PASS" > ~/valkey.creds
  chmod 600 ~/valkey.creds

  MEMTOTAL_MB=$(free -m | grep ^Mem: | awk '{print $2}')
  MAXMEMORY_MB=$((MEMTOTAL_MB * 75 / 100))

  echo "" >> /etc/valkey/valkey.conf
  echo "# Memory-optimized settings for small-scale deployments" >> /etc/valkey/valkey.conf
  echo "maxmemory ${MAXMEMORY_MB}mb" >> /etc/valkey/valkey.conf
  echo "maxmemory-policy allkeys-lru" >> /etc/valkey/valkey.conf
  echo "maxmemory-samples 10" >> /etc/valkey/valkey.conf
  msg_ok "Installed Valkey"

  echo
  read -r -p "${TAB3}Enable TLS for Valkey (Sentinel mode does not supported)? [y/N]: " prompt
  if [[ ${prompt,,} =~ ^(y|yes)$ ]]; then
    read -r -p "${TAB3}Use TLS-only mode (disable TCP port 6379)? [y/N]: " tls_only
    msg_info "Configuring TLS for Valkey..."

    create_self_signed_cert "Valkey"
    TLS_DIR="/etc/ssl/valkey"
    TLS_CERT="$TLS_DIR/valkey.crt"
    TLS_KEY="$TLS_DIR/valkey.key"
    chown valkey:valkey "$TLS_CERT" "$TLS_KEY"

    if [[ ${tls_only,,} =~ ^(y|yes)$ ]]; then
      cat << EOF > /etc/valkey/valkey.conf

# TLS configuration generated by Proxmox VE Valkey helper-script
port 0
tls-port 6379
tls-cert-file $TLS_DIR/valkey.crt
tls-key-file $TLS_DIR/valkey.key
tls-auth-clients no
EOF
      msg_ok "Enabled TLS-only mode on port 6379"
    else
      cat << EOF > /etc/valkey/valkey.conf

# TLS configuration generated by Proxmox VE Valkey helper-script
tls-port 6380
tls-cert-file $TLS_DIR/valkey.crt
tls-key-file $TLS_DIR/valkey.key
tls-auth-clients no
EOF
      msg_ok "Enabled TLS on port 6380 and TCP on 6379"
    fi
  fi

  systemctl enable -q --now valkey-server
  systemctl restart valkey-server
}

function post_install_script() {
  msg_ok "Completed successfully!\n"
  echo -e "${CREATING}${GN}${APP} setup has been successfully initialized!${CL}"
  echo -e "${INFO}${YW}Access it using the following URL:${CL}"
  echo -e "${GATEWAY}${BGN}http://${IP}:6379${CL}"
}

function update_script() {
  header_info
  check_container_storage
  check_container_resources
  if [[ ! -f /lib/systemd/system/valkey-server.service ]]; then
    msg_error "No ${APP} Installation Found!"
    exit
  fi
  msg_info "Updating ${APP} LXC"
  $STD apt update
  $STD apt -y upgrade
  msg_ok "Updated ${APP} LXC"
  msg_ok "Updated successfully!"
  exit
}

# framework bootstrap
# shellcheck disable=SC1090
# Dynamic URL resolved at runtime - shellcheck cannot follow
source <(curl -fsSL "$REPO_BASE/misc/bootstrap/lxc")
