#!/usr/bin/env bash
REPO_BASE="${REPO_BASE:-https://raw.githubusercontent.com/scripts-underground/proxmox/main}"

# Sourced by lxc.bootstrap — never executed directly
# Copyright (c) 2021-2026 community-scripts ORG
# Author: MickLesk (CanbiZ)
# License: MIT | https://raw.githubusercontent.com/scripts-underground/proxmox/main/LICENSE
# Source: https://zotregistry.dev/ | Github: https://github.com/project-zot/zot

# shellcheck disable=SC2034
# Read by the framework - shellcheck cannot see the caller
APP="Zot-Registry"
var_tags="${var_tags:-registry;oci}"
var_cpu="${var_cpu:-1}"
var_ram="${var_ram:-4096}"
var_disk="${var_disk:-5}"
var_os="${var_os:-debian}"
var_version="${var_version:-13}"
var_arm64="${var_arm64:-yes}"
var_unprivileged="${var_unprivileged:-1}"

function install_script() {
  msg_info "Installing Dependencies"
  $STD apt install -y apache2-utils
  msg_ok "Installed Dependencies"

  fetch_and_deploy_gh_release "zot" "project-zot/zot" "singlefile" "latest" "/usr/bin" "zot-linux-$(get_system_arch)"

  msg_info "Configuring Zot Registry"
  mkdir -p /etc/zot
  curl -fsSL https://raw.githubusercontent.com/project-zot/zot/refs/heads/main/examples/config-ui.json -o /etc/zot/config.json
  ZOTPASSWORD=$(openssl rand -base64 18 | tr -dc 'a-zA-Z0-9' | head -c13)
  $STD htpasswd -b -B -c /etc/zot/htpasswd admin "$ZOTPASSWORD"
  cat << EOF > ~/zot.creds
Zot-Credentials
Zot User: admin
Zot Password: $ZOTPASSWORD
EOF
  msg_ok "Configured Zot Registry"

  msg_info "Creating Service"
  cat << EOF > /etc/systemd/system/zot.service
[Unit]
Description=OCI Distribution Registry
Documentation=https://zotregistry.dev/
After=network.target auditd.service local-fs.target

[Service]
Type=simple
ExecStart=/usr/bin/zot serve /etc/zot/config.json
Restart=on-failure
User=root
LimitNOFILE=500000
MemoryHigh=2G
MemoryMax=4G

[Install]
WantedBy=multi-user.target
EOF
  systemctl enable -q --now zot
  msg_ok "Created Service"
}

function post_install_script() {
  msg_ok "Completed Successfully!\n"
  echo -e "${CREATING}${GN}${APP} setup has been successfully initialized!${CL}"
  echo -e "${INFO}${YW} Access it using the following URL:${CL}"
  echo -e "${TAB}${GATEWAY}${BGN}http://${IP}:8080${CL}"
  echo -e ""
  echo -e "${INFO}${YW} Credentials are stored in ~/zot.creds inside the container:${CL}"
  echo -e "${TAB}${BGN}  User: admin${CL}"
  echo -e "${TAB}${BGN}  Password: <auto-generated>${CL}"
}

function update_script() {
  header_info
  check_container_storage
  check_container_resources

  if [[ ! -f /usr/bin/zot ]]; then
    msg_error "No ${APP} Installation Found!"
    exit
  fi

  if check_for_gh_release "zot" "project-zot/zot"; then
    msg_info "Stopping Service"
    systemctl stop zot
    msg_ok "Stopped Service"

    rm -f /usr/bin/zot
    fetch_and_deploy_gh_release "zot" "project-zot/zot" "singlefile" "latest" "/usr/bin" "zot-linux-$(get_system_arch)"

    msg_info "Starting Service"
    systemctl start zot
    msg_ok "Started Service"
    msg_ok "Updated successfully!"
  fi
  exit
}

# framework bootstrap
# shellcheck disable=SC1090
# Dynamic URL resolved at runtime - shellcheck cannot follow
source <(curl -fsSL "$REPO_BASE/misc/bootstrap/lxc")
